name: goplaciz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Presentations
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  easy_localization: ^3.0.0
  adaptive_theme: ^2.3.0
  flutter_screenutil: ^5.3.1
  pull_to_refresh: ^2.0.0
  pinput: ^2.2.6
  timer_count_down: ^2.2.1
  animations: ^2.0.2
  intl_phone_number_input: ^0.7.0+2
  country_picker: ^2.0.12

  # Infrastructure
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  freezed: ^1.1.1
  connectivity: ^3.0.6
  dio: ^4.0.6
  get_it: ^7.2.0
  image_picker: ^0.8.4+11
  url_launcher: ^6.0.20
  quick_actions: ^0.6.0+10
  google_sign_in: ^5.2.4
  sign_in_with_apple: ^3.3.0
  flutter_login_facebook: ^1.4.1

  # Local storage
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0

  # security
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  freezed_annotation: ^1.1.0
  build_runner: ^2.1.8
  flutter_native_splash: ^2.1.3+1


flutter_native_splash:
  color: "#457FC1"
  image: assets/images/splash_screen.png
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/translations/
    - assets/images/
